spring:
  application:
    name: reservation-service
  profiles:
    active: ${PROFILE:local}
  main:
    web-application-type: reactive
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  config:
    import: "optional:configserver:http://localhost:8071/"
server:
  shutdown: graceful